project:
  type: website

website:
  title: "Carlos C. Goller"

  announcement:
    icon: info-circle
    dismissable: true
    content: "**Welcome** - this is some information that you should pay attention to"
    type: primary
    position: below-navbar
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false