project:
  type: website
  resources:
    - works.bib
    - mentoring.bib
    - assets/vendor/datatables/*

website:
  title: "Carlos C. Goller"
  favicon: ccg100.jpg
  description: Explorer of Bacterial and Learner Diversity
  page-navigation: true
  reader-mode: true
  
  navbar:
    background: "#ffffff"
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd
    right:
      - text: "More"
        menu:
          - text: "Courses"
            href: courses.qmd
          - text: "Mentoring"
            href: mentoring.qmd
          - text: "Prof. Dev"
            href: professional-development.qmd
          - text: "Contact"
            href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-before-body: skip-link.html
    toc: false

    page-footer:
      background: "#f7f5f2"
      foreground: "#4b5563"
      left: >-
        &#169; 2026 Carlos C. Goller, Ph.D.
      center: >-
        Website built with <a href="https://quarto.org/" target="_blank">Quarto</a>
        <br>Source available at <a href="https://github.com/ccgoller/" target="_blank">GitHub</a></br>
      right: >-
        Licensed under
        <br><a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank">Creative Commons Zero v1.0 Universal</a></br>
editor: source